config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :bands do
    resources :albums, only: [:new]
  end
  resources :albums, except: [:new, :index] do
    resources :tracks, only: [:new]
  end
  resources :tracks, except: [:new, :index]
  resources :notes, only: [:create, :destroy]
end

app/models/track.rb
class Track < ApplicationRecord
    validates :ord, :title, presence: true, uniqueness: {scope: :album}
    validates :title, :album_id, presence: true

    delegate :title, to: :album, prefix: true
    delegate :year, to: :album, prefix: true
    delegate :name, to: :band, prefix: true

    belongs_to :album
    has_one :band, through: :album
    has_many :notes, dependent: :destroy
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :require_logged_in!
  def new
    @album = Album.find(params[:album_id])
    @track = Track.find_by(album_id: params[:album_id])
  end

  def create
    @track = Track.new(track_params)
    if @track.save
      flash[:success] = "The track has been saved"
      redirect_to track_url(@track)
    else
      flash.now[:error] = @track.errors.full_messages
      render 'new'
    end
  end

  def edit
    @track = Track.find(params[:id])
  end

  def update
    @track = Track.find(params[:id])
    if @track.update(track_params)
      flash[:success] = "track successfully updated."
      redirect_to track_url(@track)
    else
      flash.now[:error] = @track.errors.full_messages
      render 'edit'
    end
  end

  def show
    @track = Track.includes(:notes).find(params[:id])
  end

  def destroy
    @track = Track.find(params[:id])
    if @track.destroy
      flash[:success] = "Succesfully deleted #{@track.title}"
      redirect_to album_url(@track.album)
    else
      flash.now[:error] = @track.errors.full_messages
    end
  end


  private

    def track_params
      params.require(:track).permit(:album_id, :title, :ord, :lyrics, :regular)
    end
end

app/helpers/tracks_helper.rb
module TracksHelper
    def ugly_lyrics(lyrics)
        formatted_lyrics = ""
        lyrics.lines.each do |line|
        formatted_lyrics << "&#9835; #{h(line)}"
        end

        "<pre class='lyrics'>#{formatted_lyrics}</pre>".html_safe
    end
end

app/views/tracks/edit.html.erb
<h1>Edit <%= @track.title %></h1>

<form action="<%= track_url %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="hidden" name="_method" value="PATCH">

    <p>
        <label for="title">Track title:</label>
        <input type="text" name="track[title]" id="title" value="<%= @track.title %>">
    </p>

    <p>
        <label for='track-album'>Album</label>
        <select id='track-album' name="track[album_id]">
            <% Album.all.each do |album| %>
            <option
                <%= "selected" if @track.album_id == album.id %>
                value="<%= album.id %>">
                <%= album.title %>
            </option>
            <% end %>
        </select>
    </p>

    <p>
        <label for="ord">Track order:</label>
        <input type="number" name="track[ord]" id="ord" value="<%= @track.ord %>">
    </p>

    <p>
        <label for="lyrics">Track lyrics (optional):</label>
        <br>
        <textarea name="track[lyrics]" id="lyrics" cols="30" rows="10"></textarea>
    </p>


    <p>
        Track type:
        <br>
        <label for="recording_type">Regular</label>
        <input type="radio" name="track[regular]" value="true" <%= "checked" if @track.regular %>>
        <label for="recording_type">Bonus</label>
        <input type="radio" name="track[regular]" value="false" <%= "checked" if !@track.regular %>>
    </p>

    <input type="submit" value="Update track">
</form>
<br>

<%= link_to 'Back to track page', track_path(@track), class: 'link' %>
<%= link_to "Back to album page", album_path(@track.album), class: 'link' %>

app/views/tracks/new.html.erb
<h1>New Track</h1>

<form action="<%= tracks_url %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <p>
        <label for="title">Track title:</label>
        <input type="text" name="track[title]" id="title">
    </p>

    <p>
        <label for='track-album'>Album</label>
        <select id='track-album' name="track[album_id]">
            <% Album.all.each do |album| %>
            <option
                <%= "selected" if @track.album_id == album.id %>
                value="<%= album.id %>">
                <%= album.title %>
            </option>
            <% end %>
        </select>
    </p>

    <p>
        <label for="ord">Track order:</label>
        <input type="number" name="track[ord]" id="ord">
    </p>

    <p>
        <label for="lyrics">Track lyrics (optional):</label>
        <br>
        <textarea name="track[lyrics]" id="lyrics" cols="30" rows="10"></textarea>
    </p>


    <p>
        Track type:
        <br>
        <label for="recording_type">Regular</label>
        <input type="radio" name="track[regular]" value="true">
        <label for="recording_type">Bonus</label>
        <input type="radio" name="track[regular]" value="false">
    </p>

    <input type="submit" value="Create track">
</form>
<br>

app/views/tracks/show.html.erb
<h1><%= @track.title %></h1>
<p>"<%= @track.title %>" is a single off the album <i><%= link_to @track.album_title, album_path(@track.album) %></i>, by <%= link_to @track.band_name, band_path(@track.band) %></p>

<h3>Track Details:</h3>
<section>
    <ul>
        <li>Year: <%= @track.album_year %></li>
        <li>
            Regular or bonus? 
            <% if @track.regular %>
                Regular
            <% else %>
                Bonus
            <% end %>
        </li>
        <li>This is the <%= @track.ord.ordinalize %> track on this album.</li>
    </ul>
</section>

<h3>Lyrics:</h3>
<section>
    <% if @track.lyrics.present? %>
        <%= ugly_lyrics(@track.lyrics) %>
    <% else %>
        No lyrics have been posted for this track yet.
    <% end %>
</section>

<h3>Notes:</h3>
<section>
    <% if @track.notes.present? %>
        <%= render 'notes/notes', notes: @track.notes %>
    <% else %>
        No notes for this track yet.
    <% end %>
</section>

<section>
    <h3>Write a note:</h3>
    <%= render 'notes/form', track: @track %>
</section>
<br>

<%= link_to "Edit this track", edit_track_path, class: 'link' %>