config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :bands do
    resources :albums, only: [:new]
  end
  resources :albums, except: [:new, :index] do
    resources :tracks, only: [:new]
  end
  resources :tracks, except: [:new, :index]
  resources :notes, only: [:create, :destroy]
end

app/models/album.rb
class Album < ApplicationRecord
    validates :title, presence: true, uniqueness: {scope: :band}
    validates :recording_type, inclusion: {in: %w(studio live)}
    validates :year, presence: true, numericality: true

    belongs_to :band
    has_many :tracks, dependent: :destroy

    delegate :name, to: :band, prefix: true
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
    before_action :require_logged_in!
    def new
        @band = Band.find(params[:band_id])
        @album = Album.find_by(band_id: params[:band_id])
    end

    def create
        @album = Album.new(album_params)
        if @album.save
            flash[:success] = "The album has been saved"
            redirect_to album_url(@album)
        else
            flash.now[:error] = @album.errors.full_messages
            render 'new'
        end
    end

    def show
        @album = Album.find(params[:id])
    end

    def edit
        @album = Album.includes(:band).find(params[:id])
    end

    def update
        @album = Album.find(params[:id])
        if @album.update(album_params)
            flash[:success] = "Album successfully updated."
            redirect_to album_url(@album)
        else
            flash.now[:error] = @album.errors.full_messages
            render 'edit'
        end
    end

    def destroy
        @album = Album.find(params[:id])
        if @album.destroy
            flash[:success] = "Succesfully deleted #{@album.title}"
            redirect_to band_url(@album.band)
        else
            flash.now[:error] = @album.errors.full_messages
        end
    end

    private

        def album_params
            params.require(:album).permit(:title, :year, :recording_type, :band_id)
        end

end

app/views/albums/edit.html.erb
<h1>Edit <%= @album.title %></h1>

<form action="<%= album_url %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="hidden" name="_method" value="PATCH">

    <p>
        <label for="title">Album title:</label>
        <input type="text" name="album[title]" id="title">
    </p>

    <p>
        <label for="year">Release year:</label>
        <input type="number" name="album[year]" id="year">
    </p>

    <p>
        <label for="recording_type">Studio or live?</label>
        <select name="album[recording_type]" id="recording_type">
            <option value="studio" selected>Studio</option>
            <option value="live">Live</option>
        </select>
    </p>

    <input type="submit" value="Update album">
</form>
<br>

<%= link_to 'Back to band page', band_path(@album.band) %>

app/views/albums/new.html.erb
<h1>New Album for <%= @band.name %></h1>

<form action="<%= albums_url %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <p>
        <label for="title">Album title:</label>
        <input type="text" name="album[title]" id="title">
    </p>

    <p>
        <label for="year">Release year:</label>
        <input type="number" name="album[year]" id="year">
    </p>

    <p>
        <label for="recording_type">Studio or live?</label>
        <select name="album[recording_type]" id="recording_type">
            <option value="studio" selected>Studio</option>
            <option value="live">Live</option>
        </select>
    </p>

    <input type="submit" value="Create album">
</form>
<br>

<%= link_to 'Back to band page', band_path(@band) %>

app/views/albums/show.html.erb
<h1><%= @album.title %></h1>
<p>This is an ablum by <%= link_to @album.band.name, band_path(@album.band) %>.</p>

<h3>Track List:</h3>
<%# eventually will need to change controller to display tracks sorted by ord %>
<ol>
    <% @album.tracks.each do |track| %>
        <li><%= link_to track.title, track_path(track) %>
        <%= "- Bonus" if !track.regular %> - 
        <%= link_to "edit", edit_track_path, class: 'edit_link' %>
        <%= link_to "delete", track_path(track), method: "DELETE", data: {confirm: "Are you sure?"}, class: 'delete_link' %>
        </li>
    <% end %>
</ol>

<%= link_to "Add new track", new_album_track_path(@album), class: 'link' %>
<%= link_to "Album info", album_path(@album), class: 'link' %>