config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :bands do
    resources :albums, only: [:new]
  end
  resources :albums, except: [:new, :index] do
    resources :tracks, only: [:new]
  end
  resources :tracks, except: [:new, :index]
  resources :notes, only: [:create, :destroy]
end

app/models/band.rb
class Band < ApplicationRecord
    validates :name, presence: true

    has_many :albums, dependent: :destroy
    #has_many :tracks, through: :albums
        ##not implemented until theres a use for this relation (ie an index of all the band's tracks)
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :require_logged_in!
  def index
    @bands = Band.all
  end

  def new
    @band = Band.new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_url(@band)
    else
      flash.now[:error] = @band.errors.full_messages
      render 'new'
    end
  end

  def show
    @band = Band.includes(:albums).find(params[:id])
  end

  def edit
    @band = Band.find(params[:id])
  end

  def update
    @band = Band.find(params[:id])
    if @band.update(band_params)
      flash[:success] = "Update succesful."
      redirect_to band_url(@band)
    else
      flash.now[:error] = @band.errors.full_messages
      render 'edit'
    end
  end

  def destroy
    @band = Band.find(params[:id])
    if @band.destroy
      flash[:success] = "The band \"#{@band.name}\" was sucessfuly deleted."
      redirect_to bands_url
    end
  end

  private

    def band_params
      params.require(:band).permit(:name)
    end
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/views/bands/_form.html.erb
<% action_url = band.persisted? ? band_url(band) : bands_url %>
<form action="<%= action_url %>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <p>
        <label for="name">Band name:</label>
        <input type="text" name="band[name]" id="band">
    </p>

    <input type="submit" value="Create band!">
</form>

app/views/bands/edit.html.erb
<h1>Edit <%= @band.name %></h1>
<form action="<%= band_url(@band) %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="hidden" name="_method" value="PATCH">

    <p>
        <label for="name">Band name:</label>
        <input type="text" name="band[name]" id="band">
    </p>

    <input type="submit" value="Update band!">
</form>

app/views/bands/index.html.erb
<h1>All Bands:</h1>

<ol>
    <% @bands.each do |band| %>
        <li><%= link_to band.name, band_path(band) %></li>
    <% end %>
</ol>

<%= link_to "Create new band", new_band_path, class: 'link' %>

app/views/bands/new.html.erb
<h1>Add a New Band</h1>
<%= render partial: 'form', locals: {band: @band, method: "POST"} %>

app/views/bands/show.html.erb
<h1><%= @band.name %></h1>

<% @band.albums.each do |album| %>
    <ul>
        <li><%= link_to album.title, album_path(album) %> - 
        <%= link_to "edit", edit_album_path(album), class: 'link' %> 
        <%= link_to "delete", album_path(album), method: "DELETE", data: {confirm: "Are you sure?"}, class: 'link' %>
        </li>
    </ul>
<% end %>

<br>

<%= link_to "New album", new_band_album_path(@band), class: 'link' %>