config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :bands do
    resources :albums, only: [:new]
  end
  resources :albums, except: [:new, :index] do
    resources :tracks, only: [:new]
  end
  resources :tracks, except: [:new, :index]
  resources :notes, only: [:create, :destroy]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
    
    <% if logged_in? %>
      <nav>
          <%= link_to "Home", user_path(current_user), class: 'link' %>
          <%= link_to "Bands", bands_path, class: 'link' %>
          
          <div class='user-detail'>
            <p>Logged in as: <%= current_user.name %></p>
            <form action=<%= session_url %> method='post'>
              <input type="hidden" name="_method" value="delete">
              <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
              <input type="submit" value="Sign Out">
            </form>
          </div>
      </nav>
    </header>
    <% end %>
    <div class='errors'>
      <% if flash[:error] %>
          <% flash[:error].each do |error| %>
              <ul>
                  <li><%= error %></li>
              </ul>
          <% end %>
      <% end %>
    </div>
    <div class='success'>
      <%= flash[:success] if flash[:success] %>
    </div>
    <%= yield %>
  </body>
</html>